### ISSUE TITLE
有没有测过，几百条的表单项，有大量的联动逻辑，性能如何

### ISSUE THREAD

**Issue by perfectyang** [Barrior/schema-render#1]

**Comment by Barrior** [comment]
我这边实践的有40多个表单项，也存在联动逻辑，目前是丝滑流畅的。

从代码角度分析，性能这块应该还可以，代码内部比较简洁，冗余的逻辑处理、以及深拷贝（在发版的时候为了更好的性能移除了）之类影响性能的计算不存在的。

你这边可以用现有的案例写个Demo看看呢，如果存在啥问题，可以通过codesandbox 把案例分享给我一起看看~

可以一个 FormRender 写几百条，也可以分几个 FormRender 多实例的方式来使用，具体要看应用场景~
